name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main  # Trigger deployment when code is pushed to the `main` branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image for the build

    steps:
      - uses: actions/checkout@v4  # Checkout the latest version of the repository

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'  # GitHub token for authentication
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MYAPPLICATION_000C4F99 }}'  # Firebase service account key
          channelId: live  # Deployment will go to the live channel
          projectId: myapplication-000c4f99  # Replace with your Firebase project ID
